### ISSUE TITLE
 build.sh: error: failed to build dependency 'fbthrift'

### ISSUE THREAD

**Issue by szisbest** [Thesys-lab/sosp23-s3fifo#1]
Hi author, I'm really sorry to bother you, but I'm stuck on the following steps in the process of repeating the build many times, and I hope to get your guidance, I've encountered the following error when building the cachelib, I've encountered the following error.
Consolidate compiler generated dependencies of target compiler_ast
[  0%] Building CXX object thrift/compiler/CMakeFiles/compiler_ast.dir/ast/t_const.cc.o
In file included from /home/sz/CacheLib/cachelib/external/fbthrift/./thrift/compiler/ast/t_const.h:21,
                 from /home/sz/CacheLib/cachelib/external/fbthrift/thrift/compiler/ast/t_const.cc:20:
/home/sz/CacheLib/cachelib/external/fbthrift/./thrift/compiler/ast/t_const_value.h: In member function ‘int64_t apache::thrift::compiler::t_const_value::get_integer() const’:
/home/sz/CacheLib/cachelib/external/fbthrift/./thrift/compiler/ast/t_const_value.h:118:50: error: ‘underlying’ is not a member of ‘fmt’
  118 |           "invalid const value access: {}", fmt::### underlying(kind_)));
      |                                                  ^~~~~~~~~~
/home/sz/CacheLib/cachelib/external/fbthrift/./thrift/compiler/ast/t_const_value.h: In member function ‘void apache::thrift::compiler::t_const_value::check_kind(apache::thrift::compiler::t_const_value::t_const_value_kind) const’:
/home/sz/CacheLib/cachelib/external/fbthrift/./thrift/compiler/ast/t_const_value.h:305:16: error: ‘underlying’ is not a member of ‘fmt’
  305 |           fmt::### underlying(kind_),
      |                ^~~~~~~~~~
/home/sz/CacheLib/cachelib/external/fbthrift/./thrift/compiler/ast/t_const_value.h:306:16: error: ‘underlying’ is not a member of ‘fmt’
  306 |           fmt::### underlying(expected)));
      |                ^~~~~~~~~~
make[2]: *** [thrift/compiler/CMakeFiles/compiler_ast.dir/build.make:90: thrift/compiler/CMakeFiles/compiler_ast.dir/ast/t_const.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:285: thrift/compiler/CMakeFiles/compiler_ast.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
build-package.sh: error: make failed
### build.sh: error: failed to build dependency 'fbthrift'
Thank you very much for your help.

**Comment by 1a1a11a** [comment]
Can you give more context on how system environment and how you build the cachelib library?

**Comment by szisbest** [comment]
Thank you very much for your reply, have a nice day,
Here is my environment wsl-Ubuntu22.04.2LTS.

Build with the following code 
``` git clone https://github.com/facebook/CacheLib cd CacheLib . /contrib/build.sh -d -j -v ``` 
When I build with . /contrib/build.sh -d -j -v, I can't install the packages because of network problems.

Then I use   . /contrib/build.sh
 and I get the error described above.

**Comment by 1a1a11a** [comment]
Hi @szisbest, since this is about cachelib, I think you should ask the question in corresponding repo. 
I think one solution is to use older versions to be compatible with cachelib.

**Comment by szisbest** [comment]
Ok, I will try it with an older version of the system, thanks for your help. All the best to you.
